[package]
name = "zingo_common_components"
description = "Common components for Zingo projects"
documentation = "https://github.com/zingolabs/zingo-common"
homepage = "https://github.com/zingolabs/zingo-common"
repository = "https://github.com/zingolabs/zingo-common.git"

version = "0.2.0"
edition = "2024"
license = "MIT"
[features]
for_test = []

[dependencies]
zebra-chain = { workspace = true }
