[package]
name = "zingo-netutils"
version = "4.0.0"
description = "network utility crate"
authors = ["zingo@zingolabs.org"]
edition.workspace = true
repository = "https://github.com/zingolabs/zingo-common"
homepage = "https://github.com/zingolabs/zingo-common"
license = "MIT"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
http.workspace = true
thiserror.workspace = true
tokio-rustls.workspace = true
tonic.workspace = true
lightwallet-protocol.workspace = true
tokio-stream = { workspace = true, optional = true }
zcash_client_backend = { workspace = true, optional = true }

[features]
globally-public-transparent = ["dep:tokio-stream"]
back_compatible = ["dep:zcash_client_backend"]

[dev-dependencies]
hyper-rustls.workspace = true
hyper-util.workspace = true
hyper.workspace = true
rustls-pemfile.workspace = true
tokio.workspace = true
http-body-util.workspace = true
x509-parser.workspace = true
