name: CI - Nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  reject-trailing-whitespace:
    uses: zingolabs/infrastructure/.github/workflows/trailing-whitespace.yaml@f074c3a26bf2d56f5f8bf0ac3d47e0da0539918c

  cargo-shear:
    uses: zingolabs/infrastructure/.github/workflows/cargo-shear.yaml@f074c3a26bf2d56f5f8bf0ac3d47e0da0539918c

  cargo-checkmate:
    uses: zingolabs/infrastructure/.github/workflows/cargo-checkmate.yaml@f074c3a26bf2d56f5f8bf0ac3d47e0da0539918c

  cargo-hack-build:
    uses: zingolabs/infrastructure/.github/workflows/cargo-hack.yaml@f074c3a26bf2d56f5f8bf0ac3d47e0da0539918c
    with:
      hack-subcommand: build
