name: CI - Nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  reject-trailing-whitespace:
    name: Reject trailing whitespace
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reject trailing whitespace
        run: ./utils/trailing-whitespace.sh reject

  cargo-shear:
    uses: zingolabs/infrastructure/.github/workflows/cargo-shear.yaml@906ca89b3fa926c18ef84555de11c7af5088db9a

  cargo-checkmate:
    uses: zingolabs/infrastructure/.github/workflows/cargo-checkmate.yaml@906ca89b3fa926c18ef84555de11c7af5088db9a

  cargo-hack-build:
    uses: zingolabs/infrastructure/.github/workflows/cargo-checkmate.yaml@906ca89b3fa926c18ef84555de11c7af5088db9a
    with:
      hack-subcommand: build
