name: CI - Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  pr-checks:
    uses: ./.github/workflows/ci-pr.yaml

  cargo-hack-build:
    name: Cargo Hack Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-hack
        uses: zingolabs/infrastructure/.github/actions/cargo-hack@843c3b12c87bff458154a25ccc1bbf9be09d628b
        with:
          hack-subcommand: build
