name: CI - PR

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - '**'
  pull_request:

jobs:
  reject-trailing-whitespace:
    uses: zingolabs/infrastructure/.github/workflows/trailing-whitespace.yaml@6b03f1ad04f8843d543fbae2a84360ba1c4812cc

  cargo-shear:
    name: Cargo Shear
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-shear
        uses: zingolabs/infrastructure/.github/actions/cargo-shear@6b03f1ad04f8843d543fbae2a84360ba1c4812cc

  cargo-checkmate:
    uses: zingolabs/infrastructure/.github/workflows/cargo-checkmate.yaml@6b03f1ad04f8843d543fbae2a84360ba1c4812cc

  cargo-hack-check:
    name: Cargo Hack Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-hack
        uses: zingolabs/infrastructure/.github/actions/cargo-hack@6b03f1ad04f8843d543fbae2a84360ba1c4812cc
        with:
          hack-subcommand: check
